config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'style-guide', to: 'pages#style_guide'
  get 'landing', to: 'pages#landing', as: 'landing'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'news_main', to: 'pages#news_main', as: 'news_main'
  get 'news_search', to: 'pages#news_search', as: 'news_search'
  get 'global_map', to: 'pages#global_map', as: 'global_map'

  resources :users, only: [:edit, :update, :show, :destroy]

  resources :lists, only: [:new, :create, :destroy, :edit, :update]

  resources :favorite_lists, only: :create

  resources :favorites, only: [:edit, :update, :destroy]

  resources :articles do
    resources :favorites, only: [:new, :create]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  after_initialize :set_defaults

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
  against: [ :title, :description, :body],
  using: {
    tsearch: { prefix: true }
  }

  # multisearchable against: [:title, :description]

  validates :title, :url, :publish_time, presence: true
  belongs_to :source
  has_many :article_keywords
  has_many :keywords, through: :article_keywords

  def set_defaults
    self.description ||= ''
    self.title ||= 'No title'
  end

end

app/models/article_keyword.rb
class ArticleKeyword < ApplicationRecord
  belongs_to :keyword
  belongs_to :article
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
  has_many :favorite_lists, dependent: :destroy
  has_many :lists, through: :favorite_lists
end

app/models/favorite_list.rb
class FavoriteList < ApplicationRecord
  belongs_to :list
  belongs_to :favorite
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:word]

  validates :word, presence: true
  has_many :article_keywords
  has_many :articles, through: :article_keywords
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :favorite_lists
  has_many :favorites, through: :favorite_lists

  validates :name, presence: true

end

app/models/source.rb
class Source < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name]

  has_many :articles
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :favorites, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :favorite_lists, through: :lists

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def after_sign_in_path_for(user)
    news_main_path
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end
end

app/controllers/favorite_lists_controller.rb
class FavoriteListsController < ApplicationController
  def create
    # 1. create a new instance of FavoriteList.new
    @favorite_list = FavoriteList.new

    # 2. find the List using the params from form
    # 3. find the Favorite using the params from form
    @list = List.find(params["favorite_list"]["list_id"])
    @favorite = Favorite.find(params["favorite_list"]["favorite_id"])
    # 4. attach Favorite and List to @favorite_list
    @favorite_list.list = @list
    @favorite_list.favorite = @favorite
    # 5. save
    @favorite_list.save!
    # 6. redirect to dashboard path
    redirect_to dashboard_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[show edit destroy update]

  def new
    @article = Article.find(params[:article_id])
    @favorite = Favorite.new
    # flash.notice = "Added to favorites."
  end

  def create
    @favorite = Favorite.new
    @favorite.user = current_user
    @favorite.article = Article.find(params[:article_id])
    @favorite.save!
    flash.notice = "Favorite saved!"
    redirect_to dashboard_path
  end

  def update
    @favorite.update(favorite_params)
    # redirect_to dashboard_path
  end

  def edit; end

  def show; end

  def destroy
    @favorite.destroy
    redirect_to dashboard_path
  end

  private

  def favorite_params
    params.permit(:note)
  end

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def new
    @keyword = Keyword.new
  end

  def index
    @keywords = Keyword.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @favorite = Favorite.find(params[:favorite_id])
    @list = List.new
  end

  def create
    @list = List.new
    @list.user = current_user
    if params["list"][:name]
      @list.name = params["list"][:name]
    end
    if @list.save
      redirect_to dashboard_path
      flash.notice = "List saved!"
    else
      redirect_to dashboard_path
    end
  end

  def edit
  end


  def update
  end

  def destroy
  end

  private

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :style_guide]

  def home
  end

  def style_guide
  end

  def landing
  end

  def dashboard
    @favorites = current_user.favorites.order(created_at: :desc)
    @lists = current_user.lists
    @favorite_lists = current_user.favorite_lists
  end

  def news_main
    @keywords = ['Covid', 'Italy', 'China', 'Wuhan', 'Corona', 'Election', 'Asx', 'Toilet paper', 'News']
    if params[:query].present?
      @articles = Article.search_by_title_and_description(params[:query]).to_json.html_safe
      # @articles = PgSearch.multisearch(params[:query])
    else

      @articles = Article.order("RANDOM()").all.first(130).to_json.html_safe

      # @articles = Article.all.last(2000).to_json.html_safe
    end
  end

  def global_map
  end

  def news_search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def edit; end

  def show

  end

  def update
    @user.update!(user_params)
    if @user.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :photo, :first_name, :last_name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/articles/_article_form.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :body %>
  <%= f.input :url %>
  <%= f.input :image_url %>
  <%= f.input :publish_time %>
  <%= f.input :sentiment %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.button :submit %>
<% end %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/favorites/_favorite_form.html.erb
<%= simple_form_for([@article, @favorite]) do |f| %>
  <%= f.input :note %>
  <p style="display: flex;justify-content: center; margin-top: 30px;"><strong><%= link_to "Create", article_favorites_path, method: :post %></strong></p>
<% end %>

app/views/favorites/edit.html.erb
<h1>Favorites#edit</h1>
<%= render partial: "favorite_form"%>
<p>Find me in app/views/favorites/edit.html.erb</p>

app/views/favorites/new.html.erb
<body>
  <% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

  <div class="view" style="background-image: url('https://images.unsplash.com/photo-1542323515918-d1939b6b84c2'); background-repeat: no-repeat; background-size: cover; background-position: center center; height: 100%; opacity: 1">
    <br>
    <h1 style="text-align:center">Create new Favorite</h1>
    <br>
    <div class="container" style="display: flex;justify-content: center; padding: 44px;">
      <div class="card" style="width: 400px; padding: 20px; opacity: 1;">
        <%= render partial: "favorite_form"%>
      </div>
    </div>
  </div>
</body>

app/views/favorites/show.html.erb
<h1>Favorites#show</h1>
<p>Find me in app/views/favorites/show.html.erb</p>

app/views/keywords/index.html.erb
<h1>Keywords#index</h1>
<p>Find me in app/views/keywords/index.html.erb</p>

app/views/keywords/new.html.erb
<h1>Keywords#new</h1>
<p>Find me in app/views/keywords/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<%= meta_description %>">
    <title><%= meta_title %></title>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <title>Vestigium</title>
    <%= favicon_link_tag asset_path('globe.ico') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <!-- <div class="main-html-container"> -->
      <%= yield %>
    <!-- </div> -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_add_to_list.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal<%= favorite.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModal<%= favorite.id %>Label" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Which list do you want to add it to?</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <!-- create a form which shows the list option -->
      <%= simple_form_for FavoriteList.new do |f| %>
        <%= f.input :list_id, as: :select, collection: List.where(user: current_user) %>
        <%= f.input :favorite_id, as: :hidden, :input_html => { :value => favorite.id } %>
    </div>
    <div class="modal-footer">
      <button type="button" class="favorite-delete-button">
        <%= f.button :submit, :class => "favorite-delete-button" %>
      </button>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-lg-2" id="left-col">
      <% if current_user.photo.attached? %>
        <%= image_tag current_user.photo, id: "dashboard-avatar-img" %>
      <% else %>
        <%= cl_image_tag 'https://res.cloudinary.com/dvbejvnhk/image/upload/v1583824016/avatar_if7whz.png', id: "dashboard-avatar-img" %>
      <% end %>
      <div id="dashboard-avatar-name">

      <% if current_user.first_name && current_user.last_name %>
        <h3><%= current_user.first_name + " " + current_user.last_name %></h3>
      <% end %>
      <% if current_user.address %>
        <h5><%= current_user.address %> </h5>
      <% end %>
      <h5><%= current_user.email %></h5>
      <h6>You have <%= @favorites.size  %> favourites</h6>

      </div>
      <%= link_to "Edit profile", edit_user_path(current_user),
      :id => "edit-profile-button" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, :id => "edit-profile-button", :class => "logout-button" %>
    </div>

    <div class="col-md-9 col-lg-10">
      <h2 id="favorite-title">Favourites</h2>
      <ul class="favorites-list" id="favorite-container">
      <!-- <div class="favorites-list"> -->
        <% @favorites.each do |favorite| %>
          <li class="favorite">

            <div class="favorite-delete-div">
                <%= link_to '<i class="fas fa-times-circle"></i>'.html_safe,
                  favorite_path(favorite),
                  method: :delete, :class => "favorite-delete-button" %>
            </div>

            <div class="favorite-note-div">
              <%= simple_form_for(favorite) do |f| %>
                <%= f.input :note, as: :text, autofocus: true,
                :input_html => {:style => 'width: 100%', :rows => 5,
                :class => "js-note-field", :id => "#{favorite.id}", "data-patch-url": favorite_path(favorite) } %>
              <% end %>
            </div>

            <div class="favorite-article">
              <div class="favorite-article-div">
                <%= image_tag favorite.article.image_url, :class => "favorite-article-img" %>
              </div>

              <div class="favorite-link">
                <p> <%= link_to "#{favorite.article.title}", favorite.article.url %></p>
              </div>
            </div>
          </li>
          <%= render partial: "add_to_list", locals: { favorite: favorite } %>
        <% end %>

      </ul>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'dashboard' %>

app/views/pages/global_map.html.erb
<div class="main-home-container globalMap-section">


  <!-- <button type="button" class="btn btn-primary" style="z-index: 10;" onclick="initializeGlobalMap()">
              More info
        </button>-->

    <div id="earth_div"></div>

</div>

<script src="//www.webglearth.com/v2/api.js"></script>
<%= javascript_pack_tag 'global_map' %>

app/views/pages/home.html.erb
<div class="main-home-container">

  <div class="one-third">
    <div class="feature-text-container">
      <div class="feature-text">Featured Articles ______________</div>
      <div class="feature-title">How are you reading your news everyday?</div>
    </div>
    <a href="#" class="red-square">
      <h6 class="square-text">Subsribe to our newsletter</h6>
      <div class="overlay-text first">NewsPaper</div>
      <div class="overlay-text next">NewsPaper</div>
      <div class="overlay-text last">NewsPaper</div>
    </a>
  </div>

  <div class="two-third">
    <div class="feature-text-container">
      <div class="feature-title">We offer a way to keep track of breaking news around you.</div>
      <div class="feature-text"> ____________________________</div>
    </div>
    <a href="/news_main" class="red-tag">
      <h6>Start reading now <i class="far fa-paper-plane"></i></h6>
    </a>
    <div class="square-container">
      <a href="/users/sign_up" class="black-square">
        <div >
          <h3>Sign up</h3>
          <h6>or Login if you already have an account</h6>
        </div>
      </a>
      <a href="/news_search" class="white-square">
        <div >
          <h3>Search for News?</h3>
          <h6>Click here</h6>
        </div>
      </a>
    </div>
  </div>



</div>


<!--
  <button type="button" class="btn btn-info"><%#= link_to 'Start Now', new_user_session_path %></button>
  <h1>Vestigium</h1>
  <h2>Pages#Landing</h2>

  <p>Find me in app/views/pages/home.html.erb</p> -->

app/views/pages/landing.html.erb
<div class="container">
  <h1> Main Page</h1>

<section>
  <h2>Nav bar</h2>
</section>

<hr/>
<!--
<section class="keyword-tags-section">
  <div class="taglist" style="display: flex;">
    <div class="flash" style="display: flex; margin: 2px;">
      <a class="post-tag js-gps-track" href=""><strong>SearchTag</strong></a>
      <a data-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
   </div>
   <div class="flash" style="display: flex; margin: 2px;">
      <a class="post-tag js-gps-track" href=""><strong>SearchTag</strong></a>
      <a data-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
   </div>
  </div>
</section>

<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
  </div>
</form>

<section>

  <h2>Article</h2>
    <div class="article">
      <h2 class="article-headline">Search for passengers exposed to coronavirus case  on flight to Sydney</h2>
      <h3 class="article-source">The Sydney morning herald</h3>
      <div class="article-photo">
        <img class="article-photo-image" src="" alt="">
        <div class="article-photo-caption"> A dog in playing</div>
      </div>
      <div class="article-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce accumsan nunc in erat hendrerit pharetra. Donec finibus est in turpis sagittis, laoreet eleifend nisi vestibulum.</div>
    </div>
</section>

<hr/>

<section>
  <h2>Map</h2>
</section>
 -->

app/views/pages/news_main.html.erb
<div class="main-home-container news-section">
  <div id="loading-screen"></div>

  <div id="three-container"></div>


  <div id="three-menu">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
      <div class="btn-group mr-2" role="group" aria-label="First group">
        <button id="table" class="btn btn-secondary corner-left">Compress</button>
        <button id="sphere" class="btn btn-secondary">Expand</button>
        <button id='onlyColor' class="btn btn-secondary corner-right">Colorization</button>
      </div>
      <div class="btn-group mr-2" role="group" aria-label="Second group">
         <button id='negative' class="btn btn-secondary corner-left">Negative</button>
        <button id='neutral' class="btn btn-secondary">Neutral</button>
        <button id='positive' class="btn btn-secondary corner-right">Positive</button>
      </div>
    </div>

    <div class="btn-group mr-3" role="group" aria-label="Third group">
      <%= form_for :global_map, url: global_map_path, method: :get do |f| %>
            <%= f.submit 'News Global Map', class: 'btn btn-secondary btn-map' %>
      <% end %>
    </div>
  </div>

  <div class="search-card">
    <%= form_tag news_main_path,
      class: '',
      id: 'search-field-div',
      method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-input",
        id: 'search-field',
        placeholder: "Find a keyword"
      %>
      <span class="input-group-btn">
        <%= button_tag 'search', class: " search-btn", id: "submit-search-btn" do %>
        <i class="fas fa-search"></i>
        <% end %>
      </span>
    <% end %>

     <div>
      <%= form_tag news_main_path, class: 'keyword', method: :get do %>
        <% @keywords.each do |word| %>
          <%= button_tag :query, class: 'keyword-btn', value: word, name: 'query' do %> <%= word %> <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="modals-container"></div>

</div>


<script>
  let dataJson = <%= @articles %>;
</script>
<%= javascript_pack_tag 'news_main' %>

app/views/pages/news_search.html.erb
<div class="main-home-container news-section">
  <div id="loading-screen">
    <p>...Please type in any search keywords...</p>
  </div>

  <div id="three-container"></div>

  <div id="three-menu">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
      <div class="btn-group mr-2" role="group" aria-label="First group">
          <button class="btn btn-secondary corner-left" id="table">Compress</button>
          <button class="btn btn-secondary corner-right" id="sphere">Expand</button>

      </div>
    </div>
  </div>

  <div class="search-card">
    <form id="search-field-div">
        <input type="text" name='search-field' id='search-field' placeholder="Search..." class="form-control search-input">
        <span class="input-group-btn">
          <button type='submit' id="submit-search-btn" class="search-btn"><i class="fas fa-search"></i></button>
        </span>
    </form>
  </div>


  <div id="modals-container"></div>

</div>


<%= javascript_pack_tag 'news_search' %>
<!-- <script src="packs/js/news_search.js">

</script> -->

app/views/pages/style_guide.html.erb
Hello!
<div class="container">

<section>
  <h2>Nav bar</h2>
  <div id="nav-bar">
    <div id="nav-logo" class="nav-element">
      <%= image_tag "logo.png", alt: "Vestigium", width: 200 %>
    </div>
    <div id="search-field-div" class="nav-element">
      <input type="text" name=search-field id="search-field" placeholder="Search...">
      <button id="search-button"><i class="fas fa-search"></i></button>
    </div>

    <div id="user-avatar" class="nav-element">
      <%= image_tag "Avatar.png", alt: "avatar", width: 50 %>
    </div>
  </div>
</section>

<hr/>

<section>
  <h2>Article</h2>

  <div class="article">
    <h2 class="article-headline">Search for passengers exposed to coronavirus case  on flight to Sydney</h2>
    <h3 class="article-source">The Sydney morning herald</h3>
    <div class="article-photo">
      <img class="article-photo-image" src="" alt="">
      <div class="article-photo-caption"> A dog in playing</div>
    </div>
    <div class="article-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce accumsan nunc in erat hendrerit pharetra. Donec finibus est in turpis sagittis, laoreet eleifend nisi vestibulum.</div>
  </div>
</section>

<hr/>

<section>
  <h2>Map</h2>

  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</section>

<hr/>

<section>
  <h2>Search field</h2>
  <div id=search-div>
    <input type="text" name=search-field id=search-field placeholder="Search...">
    <button id="search-button"><i class="fas fa-search"></i></button>
  </div>
</section>

<hr/>

<section>
  <h2>Keyword tags</h2>
</section>

<hr/>

<section>
  <h2>user menu</h2>
</section>

<hr/>

<section>
  <h2>Card</h2>
</section>

<hr/>

<section>
  <h2>Form</h2>
</section>

<hr/>

<section>
  <h2>Textfield/password</h2>
</section>

<hr/>

<section>
  <h2>Tag search</h2>
</section>

<hr/>

<section>
  <h2>Typography</h2>
</section>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to news_main_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/thetravelusts/image/upload/v1583367373/Vestigium/logoWhite-vestigium_jl6geo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <!--
        <li class="nav-item">
          # <%= link_to "Real-time Searching", news_search_path, class: "nav-link" %>
        </li>
        -->
        <li class="nav-item">
          <%= link_to "Analysing News", news_main_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= link_to image_tag(current_user.photo, :alt => "User avatar", :class => "avatar-bordered dropdown-toggle"), dashboard_path %>
          <% else %>
            <%= link_to image_tag('https://res.cloudinary.com/thetravelusts/image/upload/v1583901692/Vestigium/astrona_ozwvk7.png', :alt => "User avatar", :class => "avatar-bordered dropdown-toggle"), dashboard_path %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<h1 style="text-align:center">User Page</h1>
<div class="container" style="display: flex;justify-content: center;">
  <div class="card" style="width: 400px;">
    <div class="profile-picture" style="padding: 20px;">
      <% if current_user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, crop: :fit, class: "card-img-top" %>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/dvbejvnhk/image/upload/v1583824016/avatar_if7whz.png", class: "card-img-top" %>
            <% end %>
    </div>
    <div class="card-body">
      <p><strong>Email: </strong><%=current_user.email%></p>
      <p><strong>First name: </strong><%=(current_user.first_name == '') ? "no first name set" : current_user.first_name %></p>
      <br>
      <p><strong>Last name: </strong><%=(current_user.last_name == '') ? "no last name set" : current_user.last_name %></p>
      <br>
      <p><strong>Address: </strong><%=(current_user.first_name == '') ? "no address set" : current_user.address %></p>


      <%= link_to "Edit User", edit_user_path(current_user) %>

    </div>
  </div>
</div>
<br>
<br>